FROM python:3.12-slim

RUN useradd -ms /bin/bash app
WORKDIR /home/app

ENV RUNNING_DOCKER=1
ENV PYTHONPATH=/home/app

# system deps
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        poppler-utils \
    && rm -rf /var/lib/apt/lists/*

#PyPi
RUN pip install --no-cache-dir unit3dwebup==0.0.19rc6

USER app

EXPOSE 8000

CMD ["uvicorn", "unit3dwup.start:app", "--host", "0.0.0.0", "--port", "8000"]