services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    container_name: backend_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCKER=true
    volumes:
      - ${PREFS__SCAN_PATH}:/app/scan
      - ${PREFS__WATCHER_PATH}:/app/watcher
      - ${PREFS__WATCHER_DESTINATION_PATH}:/app/watcher_destination_path
      - ${PREFS__TORRENT_ARCHIVE_PATH}:/app/torrent_archive
      - ${ENV_PATH}:/app/.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_app
    ports:
      - "8080:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  redis_data:
