# -*- coding: utf-8 -*-

# Based on 0.8.21
# TODO 'Crews and Games ID IGDB' add it later
crew_patterns = [
    "NOGRP", "LIGHTFORCE", "SUXXORS", "KAOS", "GOG", "TENOKE", "I_KNOW", "RAZOR1911", "RUNE", "FITGIRL",
    "ELAMIGOS", "RAZORDOX", "RAZOR", "SKIDROW", "DINOBYTES", "TINYISO", "FCKDRM", "FLT", "SKIDROW",
    "CPY", "RELOADED", "HIVE", "VACE", "CZW", "PHOENIX", "JAGUAR", "CRIMSON", "TURBO", "DUPLEX", "CODEX"
]

platform_patterns = ["IOS", "LIN", "MACOS", "NINTENDO", "OCULUS", "PC", "PS4", "PS5", "PSN", "PSVR", "STEAM",
                     "STEAMVR", "XBX", "XONE", "NSW"]

additions = ["build", "complete", "definitive", "dlc", "edition", "episode", "pack", "patch", "remake", "remaster",
             "season", "update", "ultimate", "version"]

############################################# BAN LIST FOR TITLE GENERATOR #############################################
BAN_LIST = {
    "dummy" : "banned",
    "video_encoder": "banned"
}

#################################################### TITLE GENERATOR ###################################################
TAGS_LIST = {
            "REMUX": "remux",
            "WEB-DL": "source",
            "WEBDL": "source",
            "WEB-DLRIP": "source",
            "WEBDLRIP": "source",
            "WEB-DLMUX": "source",
            "WEBDLMUX": "source",
            "WEB-MUX": "source",
            "WEBMUX": "source",
            "WEBRIP": "source",
            "BD-UNTOUCHED": "source",
            "UNTOUCHED": "source",
            "FULL DISC": "source",
            "ENCODE": "source",
            "DLMUX": "source",
            "BDMUX": "source",
            "DVDMUX": "source",
            "CINEMA": "source",

            "3D": "source",
            "TS": "source",
            "CAM": "source",
            "HDTS": "source",
            "MD": "source",
            "UHDRIP": "source",
            "BLURAY": "source",
            "BRRIP": "source",
            "BDRIP": "source",
            "FHDRIP": "source",
            "PDTV": "source",
            "SATRIP": "source",
            "DVBRIP": "source",
            "DVB-S": "source",
            "DTTRIP": "source",
            "WP": "source",
            "DVDSCR": "source",
            "TVRIP": "source",
            "VHSRIP": "source",
            "DVDRIP": "source",
            "HDTV": "source",
            "DVD5": "source",
            "DVD9": "source",
            "VU": "source",

            "ATVP": "platform",
            "AMZN": "platform",
            "AMC": "platform",
            "CN": "platform",
            "CR": "platform",
            "DCU": "platform",
            "DSCP": "platform",
            "DSNY": "platform",
            "DSNP": "platform",
            "DPLY": "platform",
            "ESPN": "platform",
            "FOOD": "platform",
            "FOX": "platform",
            "PLAY": "platform",
            "HBO": "platform",
            "HMAX": "platform",
            "HGTV": "platform",
            "HIST": "platform",
            "HULU": "platform",
            "MTOD": "platform",
            "NATG": "platform",
            "NF": "platform",
            "NICK": "platform",
            "NOW": "platform",
            "PMNT": "platform",
            "PMTP": "platform",
            "PCOK": "platform",
            "RKTN": "platform",
            "SHO": "platform",
            "SKST": "platform",
            "STAN": "platform",
            "STRP": "platform",
            "STZ": "platform",
            "TIMV": "platform",

            "SPECIAL": "version",
            "REPACK": "version",
            "EXTENDED": "version",
            "EDITION": "version",
            "DIRECTOR'S": "version",
            "CUT": "version",
            "RERIP": "version",

            "COLLECTION": "version",
            "SUBBED": "version",
            "MUX": "version",
            "REMASTERED": "version",
            "READNFO": "version",
            "UNRATED": "version",
            "UNCUT": "version",
            "LIMITED": "version",
            "ANNIVERSARY": "version",
            "4k RESTORATION": "version",
            "IMAX": "version",
            "OPEN MATTE": "version",
            "2IN1": "version",

            "STV": "version",
            "RECODE": "version",
            "INTERNAL": "version",
            "PROPER": "version",
            "DUAL": "version",
            "COMPLETE": "version",
            "COMPLETA": "version",

            "X264": "video_encoder",
            "X265": "video_encoder",
        }

###################################################### RELEASERS #######################################################
SIGNS_LIST = {
    "21APRILE": "releaser",
    "ACCID": "releaser",
    "ADWEB": "releaser",
    "ALE88SERMETE": "releaser",
    "APEX": "releaser",
    "ARMOR": "releaser",
    "ARRANCAR": "releaser",
    "ARTEMIX": "releaser",
    "ARTEMIX MIRCREW": "releaser",
    "ASPIDE MIRCREW": "releaser",
    "ASTOR": "releaser",
    "AV1MERR": "releaser",
    "BADGUY": "releaser",
    "BALTHA": "releaser",
    "BAMAX71": "releaser",
    "BD": "releaser",
    "BEN THE MEN": "releaser",
    "BITSHIFT": "releaser",
    "BLACKBIT": "releaser",
    "BL4CK-B4RT-MIRCREW": "releaser",
    "BLUWORLD": "releaser",
    "BOBDOBBS": "releaser",
    "BONE": "releaser",
    "BULLITT": "releaser",
    "BUMBLEBEE1982": "releaser",
    "BUREK": "releaser",
    "C0P": "releaser",
    "CAPPYO": "releaser",
    "CAVALLONZI": "releaser",
    "CB01HD": "releaser",
    "CHD": "releaser",
    "CHDWEB": "releaser",
    "CIAME": "releaser",
    "CLOCLONE": "releaser",
    "CODEX": "releaser",
    "COMIX21": "releaser",
    "CREW": "releaser",
    "CSS": "releaser",
    "CSS2": "releaser",
    "CSS7896": "releaser",
    "CYBER": "releaser",
    "D3VELOPER": "releaser",
    "DAICHISO": "releaser",
    "DANGUARD": "releaser",
    "DARKCOMPANY": "releaser",
    "DARKPARANOR": "releaser",
    "DAYMON64": "releaser",
    "DB": "releaser",
    "DDN": "releaser",
    "DDNCREW": "releaser",
    "DEDO1911": "releaser",
    "DEMN": "releaser",
    "DMAN": "releaser",
    "DOCH74": "releaser",
    "DR4GON": "releaser",
    "DRIIP": "releaser",
    "DST": "releaser",
    "DYNUX": "releaser",
    "EA": "releaser",
    "EGL": "releaser",
    "ELGHOTO": "releaser",
    "ELISA": "releaser",
    "EMPRESS": "releaser",
    "ENCRYPTED": "releaser",
    "EPSILON": "releaser",
    "EVN": "releaser",
    "EZTV": "releaser",
    "FAINO1310": "releaser",
    "FEDECAS89": "releaser",
    "FGT": "releaser",
    "FHC": "releaser",
    "FLIPU": "releaser",
    "FLT": "releaser",
    "FLORIN993": "releaser",
    "FLUX": "releaser",
    "FOOD": "releaser",
    "FRAMESTOR": "releaser",
    "FREZEEN": "releaser",
    "FW": "releaser",
    "FUSION": "releaser",
    "FXE": "releaser",
    "G66": "releaser",
    "GABIACAS": "releaser",
    "GATTOPOLLO": "releaser",
    "GEGE": "releaser",
    "GFM": "releaser",
    "GIUSEPPETNT": "releaser",
    "GOLDENTORRENT": "releaser",
    "GRYM": "releaser",
    "HAPPITEAM-YNK": "releaser",
    "HASHDEV": "releaser",
    "HDCHINA": "releaser",
    "HDI": "releaser",
    "HHNN": "releaser",
    "HHWEB": "releaser",
    "HENRYDIRTY": "releaser",
    "HMR": "releaser",
    "HONE": "releaser",
    "HYRULE": "releaser",
    "I3AM": "releaser",
    "IBANEZ89": "releaser",
    "IDIB": "releaser",
    "IDN": "releaser",
    "IDN-CREW": "releaser",
    "IGS": "releaser",
    "ILGANZO": "releaser",
    "ILPADRINO": "releaser",
    "ILSAGGIO": "releaser",
    "ILSOMMO": "releaser",
    "IPDR01": "releaser",
    "ITT": "releaser",
    "JEDDAK-MIRCREW": "releaser",
    "JOHNSEED": "releaser",
    "K-Z": "releaser",
    "KARIDO": "releaser",
    "KINGOFROME": "releaser",
    "KIN": "releaser",
    "KISSY": "releaser",
    "KITSUNE": "releaser",
    "KJM": "releaser",
    "KOGI": "releaser",
    "KONTRAST": "releaser",
    "KOVALSKI": "releaser",
    "KRALIMARKO": "releaser",
    "KRIKK": "releaser",
    "KUCHU": "releaser",
    "LAZY-SUBS": "releaser",
    "LATENEVER": "releaser",
    "LDI": "releaser",
    "LEAGUENF": "releaser",
    "LELE753": "releaser",
    "LEPORE": "releaser",
    "LFI": "releaser",
    "LICDOM": "releaser",
    "LOZIO-MIRCREW": "releaser",
    "LULLOZZO": "releaser",
    "LZ": "releaser",
    "LAXII": "releaser",
    "LZ59": "releaser",
    "MADHEX": "releaser",
    "MADSKY": "releaser",
    "MADTIA": "releaser",
    "MAX": "releaser",
    "MEM.GP" : "releaser",
    "MEMGP": "releaser",
    "MEM": "releaser",
    "MAX2014": "releaser",
    "ME7ALH": "releaser",
    "MIK0YAN": "releaser",
    "MIRCREW": "releaser",
    "MISTERNED": "releaser",
    "MORPHEUS": "releaser",
    "MRBLONDE": "releaser",
    "MRROBOT": "releaser",
    "MUETTO": "releaser",
    "MUWATTALI": "releaser",
    "NAHOM": "releaser",
    "NARSETE": "releaser",
    "NEOSTARK": "releaser",
    "NEUROSIS": "releaser",
    "NIMOUEH": "releaser",
    "NOGROUP": "releaser",
    "NOMADS": "releaser",
    "NOVARIP": "releaser",
    "NTB": "releaser",
    "NTROPIC": "releaser",
    "ODS": "releaser",
    "ODINO": "releaser",
    "ONGOIA": "releaser",
    "PASO77": "releaser",
    "PEPPE": "releaser",
    "PENNYWISE": "releaser",
    "PETE321": "releaser",
    "PICOPOCO": "releaser",
    "PING": "releaser",
    "PINKER": "releaser",
    "PIR8": "releaser",
    "PLAYWEB": "releaser",
    "PLUSAM": "releaser",
    "POKE": "releaser",
    "PRIME": "releaser",
    "PROMETHEUS": "releaser",
    "PROSCIUTTO": "releaser",
    "RADESE": "releaser",
    "RAPTA": "releaser",
    "RARBG": "releaser",
    "RAWR": "releaser",
    "REALDMDJ": "releaser",
    "RIDDICKK": "releaser",
    "RMTEAM": "releaser",
    "ROMEO": "releaser",
    "RUNE": "releaser",
    "RYUKXX": "releaser",
    "S-K": "releaser",
    "SAW": "releaser",
    "SANDWORM": "releaser",
    "SBR": "releaser",
    "SEEDBOX": "releaser",
    "SEEDBOX2": "releaser",
    "SERCIUS": "releaser",
    "SID": "releaser",
    "SIMO01": "releaser",
    "SIXTEEN8664": "releaser",
    "SK4TTO": "releaser",
    "SMURF": "releaser",
    "SMURFADMIN": "releaser",
    "SP33DY94-MIRCREW": "releaser",
    "SPWEB": "releaser",
    "SPYRO": "releaser",
    "SPYRO1989": "releaser",
    "STEFRA": "releaser",
    "STEVEJOHNNEE": "releaser",
    "STINGUAJT": "releaser",
    "TAHTAKALECI": "releaser",
    "TASKO": "releaser",
    "TELESTO": "releaser",
    "TEPES": "releaser",
    "TERMINAL": "releaser",
    "THEBLACKKING": "releaser",
    "THEEMOJICREW": "releaser",
    "THUDARA": "releaser",
    "TIGER": "releaser",
    "TIGRE67": "releaser",
    "TBR": "releaser",
    "TBZ": "releaser",
    "T4P3": "releaser",
    "TORRENTER10": "releaser",
    "TOTAL_SHARE88": "releaser",
    "TREE7458": "releaser",
    "TRITON": "releaser",
    "TRL": "releaser",
    "TSUNAMI": "releaser",
    "UBI": "releaser",
    "UH": "releaser",
    "V3SP4EV3R": "releaser",
    "VARYG": "releaser",
    "VIOLENT96": "releaser",
    "VITELLO": "releaser",
    "VOLVIC": "releaser",
    "WAR": "releaser",
    "WATCHABLE": "releaser",
    "WELP": "releaser",
    "WGZ": "releaser",
    "WHEELIE": "releaser",
    "WHITERHINO": "releaser",
    "WIGGAZ": "releaser",
    "WIZARDS2K": "releaser",
    "WRM": "releaser",
    "WRS": "releaser",
    "XFM": "releaser",
    "XVID": "releaser",
    "YIFY": "releaser",
    "YTS": "releaser",
    "YTS.BZ": "releaser",
    "ZIORIP": "releaser",
    "ZK": "releaser",
    "ZODD": "releaser",
    "ZOOEYDES": "releaser",
    "ZTR": "releaser",
    "£ƐGƐND63": "releaser"
}